version: "3"

services:
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=3YMPamyXo!@B
      - MYSQL_DATABASE=spider
      - MYSQL_USER=crawler
      - MYSQL_PASSWORD=3YMPamyXo!@B
    ports:
      - "33060:3306"
    command:
      --init-file /data/init.sql
    volumes:
      - ./init.sql:/data/init.sql
      - mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  redis:
    image: "redis:alpine"
    ports:
      - "6382:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  web:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile-Web
    ports:
      - "8000:5000"
  scheduler:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile-Scheduler
  worker:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile-Worker
    deploy:
      mode: replicated
      replicas: 3

volumes:
  mysql:
