FROM python:3.12.2-alpine
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
EXPOSE 5000
COPY ./src /code

CMD ["uvicorn", "web_main:APP", "--host", "0.0.0.0", "--port", "5000"]
