FROM python:3.12.2-alpine
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./src /code

CMD ["python", "-u", "worker_main.py"]
